//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JolTudomE_Client.JolTudomEWSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.ComplexObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.Statistics))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.TestDetails))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.Courses))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.Topics))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.PersonDetails))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.Statistics))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.TestDetails))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.Courses))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.Topics))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JolTudomE_Client.JolTudomEWSService.PersonDetails))]
    public partial class ComplexObject : JolTudomE_Client.JolTudomEWSService.StructuralObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Statistics", Namespace="http://schemas.datacontract.org/2004/07/JolTudomE_WS.DAL", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Statistics : JolTudomE_Client.JolTudomEWSService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CorrectAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GeneratedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> TotalTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CorrectAnswer {
            get {
                return this.CorrectAnswerField;
            }
            set {
                if ((this.CorrectAnswerField.Equals(value) != true)) {
                    this.CorrectAnswerField = value;
                    this.RaisePropertyChanged("CorrectAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Generated {
            get {
                return this.GeneratedField;
            }
            set {
                if ((this.GeneratedField.Equals(value) != true)) {
                    this.GeneratedField = value;
                    this.RaisePropertyChanged("Generated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Percent {
            get {
                return this.PercentField;
            }
            set {
                if ((this.PercentField.Equals(value) != true)) {
                    this.PercentField = value;
                    this.RaisePropertyChanged("Percent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Questions {
            get {
                return this.QuestionsField;
            }
            set {
                if ((this.QuestionsField.Equals(value) != true)) {
                    this.QuestionsField = value;
                    this.RaisePropertyChanged("Questions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TestID {
            get {
                return this.TestIDField;
            }
            set {
                if ((this.TestIDField.Equals(value) != true)) {
                    this.TestIDField = value;
                    this.RaisePropertyChanged("TestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TotalTime {
            get {
                return this.TotalTimeField;
            }
            set {
                if ((this.TotalTimeField.Equals(value) != true)) {
                    this.TotalTimeField = value;
                    this.RaisePropertyChanged("TotalTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestDetails", Namespace="http://schemas.datacontract.org/2004/07/JolTudomE_WS.DAL", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TestDetails : JolTudomE_Client.JolTudomEWSService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChekedAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrectAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChekedAnswer {
            get {
                return this.ChekedAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChekedAnswerField, value) != true)) {
                    this.ChekedAnswerField = value;
                    this.RaisePropertyChanged("ChekedAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrectAnswer {
            get {
                return this.CorrectAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrectAnswerField, value) != true)) {
                    this.CorrectAnswerField = value;
                    this.RaisePropertyChanged("CorrectAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionText {
            get {
                return this.QuestionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTextField, value) != true)) {
                    this.QuestionTextField = value;
                    this.RaisePropertyChanged("QuestionText");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Courses", Namespace="http://schemas.datacontract.org/2004/07/JolTudomE_WS.DAL", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Courses : JolTudomE_Client.JolTudomEWSService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseDescription {
            get {
                return this.CourseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseDescriptionField, value) != true)) {
                    this.CourseDescriptionField = value;
                    this.RaisePropertyChanged("CourseDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Topics", Namespace="http://schemas.datacontract.org/2004/07/JolTudomE_WS.DAL", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Topics : JolTudomE_Client.JolTudomEWSService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TopicIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TopicDescription {
            get {
                return this.TopicDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicDescriptionField, value) != true)) {
                    this.TopicDescriptionField = value;
                    this.RaisePropertyChanged("TopicDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TopicID {
            get {
                return this.TopicIDField;
            }
            set {
                if ((this.TopicIDField.Equals(value) != true)) {
                    this.TopicIDField = value;
                    this.RaisePropertyChanged("TopicID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TopicName {
            get {
                return this.TopicNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicNameField, value) != true)) {
                    this.TopicNameField = value;
                    this.RaisePropertyChanged("TopicName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDetails", Namespace="http://schemas.datacontract.org/2004/07/JolTudomE_WS.DAL", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PersonDetails : JolTudomE_Client.JolTudomEWSService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix {
            get {
                return this.PrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefixField, value) != true)) {
                    this.PrefixField = value;
                    this.RaisePropertyChanged("Prefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewTest", Namespace="http://schemas.datacontract.org/2004/07/JolTudomE_WS.Model")]
    [System.SerializableAttribute()]
    public partial class NewTest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.NewTestQuestion> QuestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TestIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.NewTestQuestion> Questions {
            get {
                return this.QuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionsField, value) != true)) {
                    this.QuestionsField = value;
                    this.RaisePropertyChanged("Questions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TestID {
            get {
                return this.TestIDField;
            }
            set {
                if ((this.TestIDField.Equals(value) != true)) {
                    this.TestIDField = value;
                    this.RaisePropertyChanged("TestID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewTestQuestion", Namespace="http://schemas.datacontract.org/2004/07/JolTudomE_WS.Model")]
    [System.SerializableAttribute()]
    public partial class NewTestQuestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.NewTestQuestAnswer> AnswersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.NewTestQuestAnswer> Answers {
            get {
                return this.AnswersField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswersField, value) != true)) {
                    this.AnswersField = value;
                    this.RaisePropertyChanged("Answers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((this.QuestionIDField.Equals(value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionText {
            get {
                return this.QuestionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTextField, value) != true)) {
                    this.QuestionTextField = value;
                    this.RaisePropertyChanged("QuestionText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewTestQuestAnswer", Namespace="http://schemas.datacontract.org/2004/07/JolTudomE_WS.Model")]
    [System.SerializableAttribute()]
    public partial class NewTestQuestAnswer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnswerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnswerID {
            get {
                return this.AnswerIDField;
            }
            set {
                if ((this.AnswerIDField.Equals(value) != true)) {
                    this.AnswerIDField = value;
                    this.RaisePropertyChanged("AnswerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnswerText {
            get {
                return this.AnswerTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerTextField, value) != true)) {
                    this.AnswerTextField = value;
                    this.RaisePropertyChanged("AnswerText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="JolTudomEWS.org", ConfigurationName="JolTudomEWSService.JolTudomEWS")]
    public interface JolTudomEWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/Login", ReplyAction="JolTudomEWS.org/JolTudomEWS/LoginResponse")]
        string Login(out JolTudomE_Client.JolTudomEWSService.PersonDetails loggedinuser, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/Logout", ReplyAction="JolTudomEWS.org/JolTudomEWS/LogoutResponse")]
        void Logout(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/GetStatistics", ReplyAction="JolTudomEWS.org/JolTudomEWS/GetStatisticsResponse")]
        System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.Statistics> GetStatistics(string token, System.Nullable<int> personid);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/GetTestDetails", ReplyAction="JolTudomEWS.org/JolTudomEWS/GetTestDetailsResponse")]
        System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.TestDetails> GetTestDetails(string token, int testid, System.Nullable<int> personid);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/CancelTest", ReplyAction="JolTudomEWS.org/JolTudomEWS/CancelTestResponse")]
        void CancelTest(string token, int testid, int personid);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/GetCourses", ReplyAction="JolTudomEWS.org/JolTudomEWS/GetCoursesResponse")]
        System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.Courses> GetCourses(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/GetTopics", ReplyAction="JolTudomEWS.org/JolTudomEWS/GetTopicsResponse")]
        System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.Topics> GetTopics(string token, int courseid);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/NewUser", ReplyAction="JolTudomEWS.org/JolTudomEWS/NewUserResponse")]
        void NewUser(string token, string username, string prefix, string lastname, string middlename, string firstname, string password, int roleid);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/StartTest", ReplyAction="JolTudomEWS.org/JolTudomEWS/StartTestResponse")]
        JolTudomE_Client.JolTudomEWSService.NewTest StartTest(string token, int count, System.Collections.Generic.List<int> topicids);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/CheckAnswer", ReplyAction="JolTudomEWS.org/JolTudomEWS/CheckAnswerResponse")]
        void CheckAnswer(string token, int personid, int testid, int questid, System.Nullable<int> answid, bool iscomplete);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/GetUsers", ReplyAction="JolTudomEWS.org/JolTudomEWS/GetUsersResponse")]
        System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.PersonDetails> GetUsers(string token, System.Nullable<int> searchroleid);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/AddNewCourse", ReplyAction="JolTudomEWS.org/JolTudomEWS/AddNewCourseResponse")]
        void AddNewCourse(string token, string name, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/EditCourse", ReplyAction="JolTudomEWS.org/JolTudomEWS/EditCourseResponse")]
        void EditCourse(string token, int courseid, string name, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/AddNewTopic", ReplyAction="JolTudomEWS.org/JolTudomEWS/AddNewTopicResponse")]
        void AddNewTopic(string token, int courseid, string name, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="JolTudomEWS.org/JolTudomEWS/EditTopic", ReplyAction="JolTudomEWS.org/JolTudomEWS/EditTopicResponse")]
        void EditTopic(string token, int courseid, int topicid, string name, string description);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JolTudomEWSChannel : JolTudomE_Client.JolTudomEWSService.JolTudomEWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JolTudomEWSClient : System.ServiceModel.ClientBase<JolTudomE_Client.JolTudomEWSService.JolTudomEWS>, JolTudomE_Client.JolTudomEWSService.JolTudomEWS {
        
        public JolTudomEWSClient() {
        }
        
        public JolTudomEWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JolTudomEWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JolTudomEWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JolTudomEWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(out JolTudomE_Client.JolTudomEWSService.PersonDetails loggedinuser, string username, string password) {
            return base.Channel.Login(out loggedinuser, username, password);
        }
        
        public void Logout(string token) {
            base.Channel.Logout(token);
        }
        
        public System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.Statistics> GetStatistics(string token, System.Nullable<int> personid) {
            return base.Channel.GetStatistics(token, personid);
        }
        
        public System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.TestDetails> GetTestDetails(string token, int testid, System.Nullable<int> personid) {
            return base.Channel.GetTestDetails(token, testid, personid);
        }
        
        public void CancelTest(string token, int testid, int personid) {
            base.Channel.CancelTest(token, testid, personid);
        }
        
        public System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.Courses> GetCourses(string token) {
            return base.Channel.GetCourses(token);
        }
        
        public System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.Topics> GetTopics(string token, int courseid) {
            return base.Channel.GetTopics(token, courseid);
        }
        
        public void NewUser(string token, string username, string prefix, string lastname, string middlename, string firstname, string password, int roleid) {
            base.Channel.NewUser(token, username, prefix, lastname, middlename, firstname, password, roleid);
        }
        
        public JolTudomE_Client.JolTudomEWSService.NewTest StartTest(string token, int count, System.Collections.Generic.List<int> topicids) {
            return base.Channel.StartTest(token, count, topicids);
        }
        
        public void CheckAnswer(string token, int personid, int testid, int questid, System.Nullable<int> answid, bool iscomplete) {
            base.Channel.CheckAnswer(token, personid, testid, questid, answid, iscomplete);
        }
        
        public System.Collections.Generic.List<JolTudomE_Client.JolTudomEWSService.PersonDetails> GetUsers(string token, System.Nullable<int> searchroleid) {
            return base.Channel.GetUsers(token, searchroleid);
        }
        
        public void AddNewCourse(string token, string name, string description) {
            base.Channel.AddNewCourse(token, name, description);
        }
        
        public void EditCourse(string token, int courseid, string name, string description) {
            base.Channel.EditCourse(token, courseid, name, description);
        }
        
        public void AddNewTopic(string token, int courseid, string name, string description) {
            base.Channel.AddNewTopic(token, courseid, name, description);
        }
        
        public void EditTopic(string token, int courseid, int topicid, string name, string description) {
            base.Channel.EditTopic(token, courseid, topicid, name, description);
        }
    }
}
